//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinaClientArea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contragents
    {
        public int id { get; set; }
        public Nullable<int> group_id { get; set; }
        public string path { get; set; }
        public string name { get; set; }
        public string short_name { get; set; }
        public string code { get; set; }
        public string tel { get; set; }
        public string address { get; set; }
        public Nullable<bool> vat { get; set; }
        public string comment { get; set; }
        public Nullable<int> acc_use { get; set; }
        public Nullable<int> type { get; set; }
        public string person { get; set; }
        public string driver_num { get; set; }
        public string car_model { get; set; }
        public string car_num { get; set; }
        public Nullable<byte> is_hidden { get; set; }
        public Nullable<byte> advance_type { get; set; }
        public Nullable<int> vat_type { get; set; }
        public Nullable<byte> pay_items { get; set; }
        public Nullable<byte> is_resident { get; set; }
        public string account { get; set; }
        public string account2 { get; set; }
        public Nullable<double> tax { get; set; }
        public Nullable<double> min_tax { get; set; }
        public Nullable<int> country_id { get; set; }
        public System.DateTime birth_date { get; set; }
        public string e_mail { get; set; }
        public int client_id { get; set; }
        public int cons_period { get; set; }
        public int create_user_id { get; set; }
        public System.DateTime create_date { get; set; }
        public int limit_type { get; set; }
        public decimal limit_val { get; set; }
        public string usr_column_501 { get; set; }
    }
}
