//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinaClientArea
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRMIncidents
    {
        public int id { get; set; }
        public int general_id { get; set; }
        public System.DateTime start_date { get; set; }
        public System.DateTime estimate_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public int priority { get; set; }
        public int incident_type { get; set; }
        public string comment { get; set; }
        public string status_comment { get; set; }
        public Nullable<int> progres_percent { get; set; }
        public int contact_id { get; set; }
    }
}
