//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinaClientArea
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinaClientAreaEntities : DbContext
    {
        public FinaClientAreaEntities()
            : base("name=FinaClientAreaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contragents> Contragents { get; set; }
        public virtual DbSet<CRMIncidentTypes> CRMIncidentTypes { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<CRMIncidents> CRMIncidents { get; set; }
        public virtual DbSet<GeneralDocs> GeneralDocs { get; set; }
        public virtual DbSet<ProductsFlow> ProductsFlow { get; set; }
    }
}
