//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinaClientArea
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralDocs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GeneralDocs()
        {
            this.ProductsFlow = new HashSet<ProductsFlow>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> tdate { get; set; }
        public Nullable<long> doc_num { get; set; }
        public string doc_num_prefix { get; set; }
        public Nullable<int> doc_type { get; set; }
        public string purpose { get; set; }
        public Nullable<double> amount { get; set; }
        public Nullable<int> currency_id { get; set; }
        public Nullable<double> rate { get; set; }
        public Nullable<double> vat { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<int> ref_id { get; set; }
        public Nullable<int> param_id1 { get; set; }
        public Nullable<int> param_id2 { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<bool> make_entry { get; set; }
        public Nullable<int> project_id { get; set; }
        public string uid { get; set; }
        public Nullable<byte> sync_status { get; set; }
        public string waybill_num { get; set; }
        public Nullable<int> store_id { get; set; }
        public Nullable<int> analytic_code { get; set; }
        public Nullable<double> amount2 { get; set; }
        public Nullable<int> contragent_sub_id { get; set; }
        public Nullable<int> contragent_id { get; set; }
        public Nullable<bool> is_blocked { get; set; }
        public Nullable<bool> is_packed { get; set; }
        public Nullable<bool> is_deleted { get; set; }
        public Nullable<int> delete_user_id { get; set; }
        public Nullable<System.DateTime> delete_date { get; set; }
        public System.DateTime create_date { get; set; }
        public int house_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsFlow> ProductsFlow { get; set; }
    }
}
