//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinaClientArea
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.ProductsFlow = new HashSet<ProductsFlow>();
        }
    
        public int id { get; set; }
        public Nullable<int> group_id { get; set; }
        public string path { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public Nullable<int> unit_id { get; set; }
        public Nullable<int> report_unit_id { get; set; }
        public Nullable<int> default_unit_id { get; set; }
        public Nullable<double> price { get; set; }
        public string comment { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<double> volume { get; set; }
        public Nullable<double> excise { get; set; }
        public Nullable<double> excise_amount { get; set; }
        public Nullable<int> country_id { get; set; }
        public string partnumber { get; set; }
        public Nullable<int> acc_use { get; set; }
        public Nullable<bool> vat { get; set; }
        public Nullable<int> vat_type { get; set; }
        public string min_Quantity { get; set; }
        public Nullable<decimal> rest_quantity { get; set; }
        public Nullable<byte> type { get; set; }
        public Nullable<byte> out_type { get; set; }
        public Nullable<double> amortization { get; set; }
        public Nullable<byte> fin_amortization_type { get; set; }
        public Nullable<byte> amortization_type { get; set; }
        public Nullable<byte> is_hidden { get; set; }
        public Nullable<byte> is_web_visible { get; set; }
        public Nullable<int> plu_code { get; set; }
        public Nullable<int> is_weight { get; set; }
        public Nullable<int> parent_id { get; set; }
        public Nullable<int> term { get; set; }
        public string uid { get; set; }
        public Nullable<byte> sync_status { get; set; }
        public Nullable<double> staff_seller { get; set; }
        public Nullable<int> inventory_group_id { get; set; }
        public Nullable<double> liquidate_value { get; set; }
        public Nullable<int> service_term { get; set; }
        public Nullable<byte> use_production { get; set; }
        public Nullable<System.DateTime> inventory_start_date { get; set; }
        public Nullable<double> fin_service_term { get; set; }
        public Nullable<System.DateTime> fin_inventory_start_date { get; set; }
        public Nullable<double> fin_amortization { get; set; }
        public Nullable<int> staff_salary_type { get; set; }
        public string series { get; set; }
        public Nullable<System.DateTime> expire_date { get; set; }
        public Nullable<System.DateTime> in_date { get; set; }
        public Nullable<bool> small_inventory { get; set; }
        public int duration { get; set; }
        public int process_type { get; set; }
        public int med_type { get; set; }
        public int client_id { get; set; }
        public int order_by { get; set; }
        public Nullable<byte> no_auto_production { get; set; }
        public int create_user_id { get; set; }
        public System.DateTime create_date { get; set; }
        public string generic_name { get; set; }
        public string replace_name { get; set; }
        public string manufacturer { get; set; }
        public string is_recipe { get; set; }
        public string max_Quantity { get; set; }
        public byte rs_code_type { get; set; }
        public int special_unit_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductsFlow> ProductsFlow { get; set; }
    }
}
